CREATE TABLE GCG_5845_POP_NOTES(
	ID IDENTITY,
	PART CHAR(20),
	LOCATION CHAR(2),
	SO_POP BIT NOT NULL ,
	Q_POP BIT NOT NULL ,
	PO_POP BIT NOT NULL ,
	SO_PRINT_ACK BIT NOT NULL ,
	SO_PRINT_PICK BIT NOT NULL ,
	SO_PRINT_PACK BIT NOT NULL ,
	SO_PRINT_INV BIT NOT NULL ,
	Q_PRINT BIT NOT NULL ,
	PO_PRINT BIT NOT NULL ,
	NOTES LONGVARCHAR
);